jwt:
  header: Authorization
  secret: MjIwNy1maXJzdC1wcm9qZWN0LWp3dC10b2tlbi1wcmVzZW50ZWQtYnktbW9nZ296aS1hbmQtc3VwcG9ydGVkLWJ5LXNzYWZ5Cg==
  cookieName: moggozi
  accessExpirationInMs: 36000000        # Access 토큰 만료 시간(ms) = 5시간
  refreshExpirationInMs: 86400000       # Refresh 토큰 만료 시간(ms) = 1일 (24시간)

spring:
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: 948844328868-f5hrdfjme3cdqgqcvd2jquoku03sgqk6.apps.googleusercontent.com
            client-secret: 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
            scope: profile, email

          naver:
            client-id: sxvlIGBRak3z0iWC1QNv
            client-secret: YOT4zpMnPj
            client-authentication-method: POST
            authorization-grant-type: authorization_code
            redirect-uri: "https://i7c201.p.ssafy.io:443/login/oauth2/code/naver"
            scope: name, email, profile_image
            client-name: Naver

          kakao:
            client-id: b0124141d1ed42c9b5218ac91637192d
            client-secret: dOji2PQP9kao6dUKxa6DoqMXl0NgC4CV
            client-authentication-method: POST
            authorization-grant-type: authorization_code
            redirect-uri: "https://i7c201.p.ssafy.io:443/login/oauth2/code/kakao"
            scope: profile_nickname, profile_image, account_email
            client-name: Kakao

        #provider
        provider:
          naver:
            authorization-uri: https://nid.naver.com/oauth2.0/authorize
            token-uri: https://nid.naver.com/oauth2.0/token
            user-info-uri: https://openapi.naver.com/v1/nid/me
            user-name-attribute: response

          kakao:
            authorization-uri: https://kauth.kakao.com/oauth/authorize
            token-uri: https://kauth.kakao.com/oauth/token
            user-info-uri: https://kapi.kakao.com/v2/user/me
            user-name-attribute: id

  mail:
    host: smtp.daum.net
    port: 465
    username: moggozi.ssafy@daum.net
    password: AhRhwl.Tkvl7
    properties:
      mail.smtp.auth: true
      mail.smtp.ssl.enable: true

#  mvc:
#    pathmatch:
#      matching-strategy: ant_path_matcher

springdoc:
  version: '@project.version@'
  api-docs:
    path: /api-docs
  default-consumes-media-type: application/json
  default-produces-media-type: application/json
  swagger-ui:
    operations-sorter: alpha
    tags-sorter: alpha
    path: /swagger-ui.html
    disable-swagger-default-url: true
    display-query-params-without-oauth2: true
    doc-expansion: none
  paths-to-match:
    - /**